apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    containerImage: quay.io/openshift-kni/oran-o2ims-operator
    description: The O-RAN O2IMS operator provides an implementation of the O-RAN
      O2 IMS API on top of OpenShift and ACM.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "false"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    olm.skipRange: '>=4.16.0 <4.18'
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    provider: Red Hat
    repository: https://github.com/openshift-kni/oran-o2ims
    support: Red Hat
  labels:
    operatorframework.io/arch.amd64: supported
  name: oran-o2ims.v4.16.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ClusterTemplate is the Schema for the clustertemplates API
      displayName: ORAN O2IMS Cluster Template
      kind: ClusterTemplate
      name: clustertemplates.o2ims.provisioning.oran.org
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      specDescriptors:
      - description: Characteristics defines a List of key/value pairs describing
          characteristics associated with the template.
        displayName: Characteristics
        path: characteristics
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Description defines a Human readable description of the Template.
        displayName: Description
        path: description
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Metadata defines a List of key/value pairs describing metadata
          associated with the template.
        displayName: Metadata
        path: metadata
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Name defines a Human readable name of the Template.
        displayName: Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Release defines the openshift release version of the template
        displayName: Release
        path: release
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: TemplateId defines a Identifier for the O-Cloud Template. This
          identifier is allocated by the O-Cloud.
        displayName: TemplateId
        path: templateId
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          TemplateParameterSchema defines the parameters required for ClusterTemplate.
          The parameter definitions should follow the OpenAPI V3 schema and
          explicitly define required fields.
        displayName: Template Parameter Schema
        path: templateParameterSchema
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Templates defines the references to the templates required for
          ClusterTemplate.
        displayName: Templates
        path: templates
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Version defines a version or generation of the resource as defined
          by its provider.
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - displayName: Conditions
        path: conditions
      version: v1alpha1
    - description: Inventory is the Schema for the Inventory API
      displayName: ORAN O2IMS Inventory
      kind: Inventory
      name: inventories.o2ims.oran.openshift.io
      resources:
      - kind: Deployment
        name: ""
        version: apps/v1
      specDescriptors:
      - description: AlarmSubscriptionServerConfig contains the configuration for
          the alarm server.
        displayName: Alarm Subscription Server Configuration
        path: alarmSubscriptionServerConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          CaBundleName references a config map that contains a set of custom CA certificates to be used when communicating
          with any outside entity (e.g., the SMO, the authorization server, etc.) that has its TLS certificate signed by
          a non-public CA certificate.
        displayName: Custom CA Certificates
        path: caBundleName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: CloudID is the global cloud ID value used to correlate the SMO
          inventory record with the deployed cloud instance.
        displayName: Cloud ID
        path: cloudID
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Deployment Manager Server Configuration
        path: deploymentManagerServerConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          Image is the full reference of the container image that contains the binary. This is
          optional and the default will be the value passed to the `--image` command line flag of
          the controller manager.
        displayName: Image
        path: image
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: IngressHost defines the FQDN for the IMS endpoints.
        displayName: Ingress Host
        path: ingressHost
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Metadata Server Configuration
        path: metadataServerConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: ResourceServerConfig contains the configuration for the resource
          server.
        displayName: Resource Server Configuration
        path: resourceServerConfig
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Backend Token
        path: resourceServerConfig.backendToken
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Backend URL
        path: resourceServerConfig.backendURL
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: This field allows the addition of extra O-Cloud information for
          the resource server.
        displayName: Extensions
        path: resourceServerConfig.extensions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: SmoConfig defines the configurable attributes to represent the
          SMO instance
        displayName: SMO Configuration
        path: smo
      - description: OAuthConfig defines the configurable attributes required to access
          the OAuth2 authorization server
        displayName: SMO OAuth Configuration
        path: smo.oauth
      - description: |-
          ClientSecretName represents the name of a secret (in the current namespace) which contains the client-id and
          client-secret values used by the OAuth client.
        displayName: Client Secret
        path: smo.oauth.clientSecretName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          Scopes represents the OAuth scope values to request when acquiring a token.  Typically, this should be set to
          "openid" in addition to any other scopes that the SMO specifically requires (e.g., "roles", "groups", etc...) to
          authorize our requests
        displayName: OAuth Scopes
        path: smo.oauth.scopes
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          TokenEndpoint represents the API endpoint used to acquire a token (e.g., /protocol/openid-connect/token) which
          will be appended to the base URL to form the full URL
        displayName: OAuth Token Endpoint
        path: smo.oauth.tokenEndpoint
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Url represents the base URL of the authorization server. (e.g.,
          https://keycloak.example.com/realms/oran)
        displayName: OAuth URL
        path: smo.oauth.url
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: RegistrationEndpoint represents the API endpoint used to register
          the O2IMS with the SMO.
        displayName: Registration API Endpoint
        path: smo.registrationEndpoint
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: TlsConfig defines the TLS attributes specific to the SMO and
          OAuth servers
        displayName: TLS Configuration
        path: smo.tls
      - description: |-
          ClientCertificateName represents the name of a secret (in the current namespace) which contains an X.509
          certificate and private key to be used when initiating connections to the SMO and OAuth servers.  The secret is
          expected to contain a 'tls.key' and 'tls.crt' keys.  If the client is signed by intermediate CA certificate(s)
          then it is expected that the full chain is to be appended to the certificate file with the device certificate
          being first and the root CA being last.
        displayName: TLS client certificate
        path: smo.tls.clientCertificateName
      - description: Url represents the base URL of the SMO instance
        displayName: SMO URL
        path: smo.url
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: Stores the local cluster ID used as the local Cloud ID value.
        displayName: Local Cluster ID
        path: clusterID
      - description: |-
          INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
          Important: Run "make" to regenerate code after modifying this file
        displayName: Conditions
        path: conditions
      - displayName: Deployments Status
        path: deploymentStatus
      - displayName: Deployment Server Status
        path: deploymentStatus.deploymentServerStatus
      - displayName: Metadata Server Status
        path: deploymentStatus.metadataServerStatus
      - displayName: Resource Server Status
        path: deploymentStatus.resourceServerStatus
      - description: |-
          Stores the ingress host domain resolved at runtime; either from a user override or automatically computed from
          the default ingress controller.
        displayName: Resolved Ingress Host Address
        path: ingressHost
      - displayName: Deployments Status
        path: usedServerConfig
      version: v1alpha1
    - description: NodePool is the schema for an allocation request of nodes
      displayName: Node Pool
      kind: NodePool
      name: nodepools.o2ims-hardwaremanagement.oran.openshift.io
      resources:
      - kind: Namespace
        name: ""
        version: v1
      specDescriptors:
      - description: |-
          CloudID is the identifier of the O-Cloud that generated this request. The hardware
          manager may want to use this to tag the nodes in its database, and to generate
          statistics.
        displayName: Cloud ID
        path: cloudID
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Extensions
        path: extensions
      - description: HwMgrId is the identifier for the hardware manager plugin adaptor.
        displayName: Hardware Manager ID
        path: hwMgrId
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Location
        displayName: Location
        path: location
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - displayName: Node Group
        path: nodeGroup
      - description: Site
        displayName: Site
        path: site
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - description: |-
          Conditions represent the observations of the NodePool's current state.
          Possible values of the condition type are `Provisioned` and `Unknown`.
        displayName: Conditions
        path: conditions
      - displayName: Hw Mgr Plugin
        path: hwMgrPlugin
      - description: Properties represent the node properties in the pool
        displayName: Properties
        path: properties
      version: v1alpha1
    - description: Node is the schema for an allocated node
      displayName: Node
      kind: Node
      name: nodes.o2ims-hardwaremanagement.oran.openshift.io
      resources:
      - kind: Namespace
        name: ""
        version: v1
      specDescriptors:
      - description: GroupName
        displayName: Group Name
        path: groupName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: HwProfile
        displayName: Hardware Profile
        path: hwProfile
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: NodePool
        displayName: Node Pool
        path: nodePool
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - displayName: BMC
        path: bmc
      - description: |-
          Conditions represent the observations of the NodeStatus's current state.
          Possible values of the condition type are `Provisioned`, `Unprovisioned`, `Updating` and `Failed`.
        displayName: Conditions
        path: conditions
      - displayName: Hostname
        path: hostname
      - displayName: Hw Profile
        path: hwProfile
      - displayName: Interfaces
        path: interfaces
      version: v1alpha1
    - description: ProvisioningRequest is the Schema for the provisioningrequests
        API
      displayName: ORAN O2IMS Provisioning Request
      kind: ProvisioningRequest
      name: provisioningrequests.o2ims.provisioning.oran.org
      resources:
      - kind: ClusterInstance
        name: ""
        version: siteconfig.open-cluster-management.io/v1alpha1
      - kind: Namespace
        name: ""
        version: v1
      specDescriptors:
      - description: Description specifies a brief description of this provisioning
          request, providing additional context or details.
        displayName: Description
        path: description
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Extensions holds additional custom key-value pairs that can be
          used to extend the cluster's configuration.
        displayName: Extensions
        path: extensions
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Name specifies a human-readable name for this provisioning request,
          intended for identification and descriptive purposes.
        displayName: Name
        path: name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          TemplateName defines the base name of the referenced ClusterTemplate.
          The full name of the ClusterTemplate is constructed as <TemplateName.TemplateVersion>.
        displayName: Template Name
        path: templateName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: TemplateParameters provides the input data that conforms to the
          OpenAPI v3 schema defined in the referenced ClusterTemplate's spec.templateParameterSchema.
        displayName: Template Parameters
        path: templateParameters
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: |-
          TemplateVersion defines the version of the referenced ClusterTemplate.
          The full name of the ClusterTemplate is constructed as <TemplateName.TemplateVersion>.
        displayName: Template Version
        path: templateVersion
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      statusDescriptors:
      - displayName: Conditions
        path: conditions
      version: v1alpha1
  description: |
    # O-RAN O2IMS operator
    The O-RAN O2IMS operator provides an implementation of the O-RAN O2 IMS API on top of OpenShift and ACM.

    ## Where to find more information
    You can find additional guidance in the [oran-o2ims repository](https://github.com/openshift-kni/oran-o2ims).
  displayName: ORAN O2IMS Operator
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ORAN
  - O2IMS
  links:
  - name: Oran O2ims
    url: https://oran-o2ims.domain
  maintainers:
  - email: jhernand@redhat.com
    name: JuanHernandez
  - email: derez@redhat.com
    name: DanielErez
  - email: imihai@redhat.com
    name: IrinaMihai
  maturity: alpha
  minKubeVersion: 1.28.0
  provider:
    name: Red Hat
  replaces: oran-o2ims.v0.0.0
  version: 0.0.1
