resources:

# Inventory:
- v1alpha1_inventory.yaml

# Hardware management:
- v1alpha1_allocatednode.yaml
- v1alpha1_nodeallocationrequest.yaml
- v1alpha1_hardwaretemplate.yaml

# Provisioning:
- v1alpha1_clustertemplate.yaml
- v1alpha1_provisioningrequest.yaml

