apiVersion: o2ims.provisioning.oran.org/v1alpha1
kind: ProvisioningRequest
metadata:
  labels:
    app.kubernetes.io/name: provisioningrequest
    app.kubernetes.io/instance: provisioningrequest-sample
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oran-o2ims
  name: provisioningrequest-sample
spec:
  name: "TestEnv-SNO-Provisioning"
  description: "Provisioning request for setting up a Single Node OpenShift (SNO) in the test environment."
  templateName: clustertemplate-sample
  templateVersion: v1.0.0
  templateParameters:
    nodeClusterName: "site-sno-du-1"
    oCloudSiteId: "local-west-12345"
    policyTemplateParameters:
      sriov-network-vlan-1: "114"
      sriov-network-vlan-2: "111"
    clusterInstanceParameters:
      apiVIPs:
        - 192.0.2.2
      additionalNTPSources:
        - NTP.server1
        - 1.1.1.1
      baseDomain: example.com
      clusterName: site-sno-du-1
      extraAnnotations:
        AgentClusterInstall:
          extra-annotation-key: extra-annotation-value
      extraLabels:
        AgentClusterInstall:
          extra-label-key: extra-label-value
        ManagedCluster:
          cluster-version: "v4.16"
          clustertemplate-a-policy: "v1"
      ingressVIPs:
        - 192.0.2.3
      machineNetwork:
        - cidr: 192.0.2.0/24
      nodes:
        - bootMode: UEFI
          extraAnnotations:
            BareMetalHost:
              extra-annotation-key: extra-annotation-value
          extraLabels:
            BareMetalHost:
              extra-label-key: extra-label-value
          hostName: node1.baseDomain.com
          nodeLabels:
            node-role.kubernetes.io/infra: ""
            node-role.kubernetes.io/master: ""
          nodeNetwork:
            config:
              dns-resolver:
                config:
                  server:
                    - 192.0.2.22
              interfaces:
                - ipv4:
                    address:
                      - ip: 192.0.2.10
                        prefix-length: 24
                      - ip: 192.0.2.11
                        prefix-length: 24
                      - ip: 192.0.2.12
                        prefix-length: 24
                    dhcp: false
                    enabled: true
                  ipv6:
                    address:
                      - ip: 2620:52:0:10e7:e42:a1ff:fe8a:601
                        prefix-length: 64
                      - ip: 2620:52:0:10e7:e42:a1ff:fe8a:602
                        prefix-length: 64
                      - ip: 2620:52:0:10e7:e42:a1ff:fe8a:603
                        prefix-length: 64
                    dhcp: false
                    enabled: true
                  name: eno1
                  type: ethernet
                - ipv6:
                    address:
                      - ip: 2620:52:0:1302::100
                    enabled: true
                    link-aggregation:
                      mode: balance-rr
                      options:
                        miimon: "140"
                      slaves:
                        - eth0
                        - eth1
                    prefix-length: 64
                  name: bond99
                  state: up
                  type: bond
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 192.0.2.254
                    next-hop-interface: eno1
                    table-id: 254
      serviceNetwork:
        - cidr: 233.252.0.0/24
      sshPublicKey: ssh-rsa
status:
  conditions: []
