apiVersion: plugins.clcm.openshift.io/v1alpha1
kind: NodeAllocationRequest
metadata:
  annotations:
    bootInterfaceLabel: bootable-interface
  generation: 1
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-sample
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oran-o2ims
  name: sample-nodeallocationrequest
  namespace: oran-hwmgr-plugin
spec:
  clusterId: sample
  hardwarePluginRef: loopback-1
  nodeGroup:
  - nodeGroupData:
      hwProfile: sample-master-profile
      name: controller
      resourcePoolId: master-pool
      role: master
    size: 1
  - nodeGroupData:
      hwProfile: sample-worker-profile
      name: worker
      resourcePoolId: worker-pool
      role: worker
    size: 0
  site: ottawa
  extensions: []
status:
  conditions:
  - lastTransitionTime: "2024-10-09T15:36:41Z"
    message: Created
    reason: Completed
    status: "True"
    type: Provisioned
  hwMgrPlugin: {}
  properties:
    nodeNames:
    - sample-node
