resources:

# Inventory:
- bases/o2ims.oran.openshift.io_inventories.yaml

# Hardware management:
- bases/o2ims-hardwaremanagement.oran.openshift.io_nodepools.yaml
- bases/o2ims-hardwaremanagement.oran.openshift.io_nodes.yaml

# Provisioning:
- bases/o2ims.provisioning.oran.org_clustertemplates.yaml
- bases/o2ims.provisioning.oran.org_clusterrequests.yaml

configurations:
- kustomizeconfig.yaml
