resources:

# Inventory:
- bases/o2ims.oran.openshift.io_inventories.yaml

# Hardware management:
- bases/o2ims-hardwaremanagement.oran.openshift.io_hardwaretemplates.yaml
- bases/o2ims-hardwaremanagement.oran.openshift.io_nodeallocationrequests.yaml
- bases/o2ims-hardwaremanagement.oran.openshift.io_allocatednodes.yaml

# Provisioning:
- bases/o2ims.provisioning.oran.org_clustertemplates.yaml
- bases/o2ims.provisioning.oran.org_provisioningrequests.yaml

#patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the **conversion** webhook for each CRD
#- patches/webhook_in_provisioning_provisioningrequests.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_provisioning_provisioningrequests.yaml
#- path: patches/cainjection_in_hardwaremanagement_hardwareplugins.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
