# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: inventory
output: ../../client/inventory/generated.go

generate:
  std-http-server: false
  client: true
  models: true
  embedded-spec: true

output-options:
  skip-fmt: false
  skip-prune: false
  nullable-type: true
  name-normalizer: ToCamelCaseWithDigits
