---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: clusterrequests.oran.openshift.io
spec:
  group: oran.openshift.io
  names:
    kind: ClusterRequest
    listKind: ClusterRequestList
    plural: clusterrequests
    singular: clusterrequest
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterRequest is the Schema for the clusterrequests API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterRequestSpec defines the desired state of ClusterRequest
            properties:
              clusterTemplateInput:
                description: JSON Schema input used for the clusterTemplateRef.
                type: string
              clusterTemplateRef:
                description: Reference to an existing clusterTemplate CR.
                type: string
            required:
            - clusterTemplateInput
            - clusterTemplateRef
            type: object
          status:
            description: ClusterRequestStatus defines the observed state of ClusterRequest
            properties:
              clusterTemplateInputValidation:
                description: Contains JSON schema and cluster template validation
                  details.
                properties:
                  inputError:
                    description: Holds the error in case the ClusterTemplateInput
                      is invalid.
                    type: string
                  inputIsValid:
                    description: Says if the ClusterTemplateInput is valid or not.
                    type: boolean
                  inputMatchesTemplate:
                    description: Says if the provided ClusterTemplateInput matches
                      the referenced ClusterTemplate.
                    type: boolean
                  inputMatchesTemplateError:
                    description: Holds the error if the provided ClusterTemplateInput
                      matches the referenced ClusterTemplate.
                    type: string
                required:
                - inputIsValid
                - inputMatchesTemplate
                type: object
              renderedTemplateStatus:
                properties:
                  renderedTemplate:
                    description: RenderedTemplate represents whether the ClusterInstance
                      template is rendered successfully
                    type: boolean
                  renderedTemplateApplied:
                    description: RenderedTemplateApplied represents whether the rendered
                      ClusterInstance is applied successfully
                    type: boolean
                  renderedTemplateAppliedError:
                    description: RenderedTemplateAppliedError holds the error if the
                      rendered ClusterInstance CR is not applied
                    type: string
                  renderedTemplateError:
                    description: RenderedTemplateError holds the error if the ClusterInstance
                      template is not rendered
                    type: string
                required:
                - renderedTemplate
                - renderedTemplateApplied
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
