---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: deploymentmanagertemplates.oran.openshift.io
spec:
  group: oran.openshift.io
  names:
    kind: DeploymentManagerTemplate
    listKind: DeploymentManagerTemplateList
    plural: deploymentmanagertemplates
    shortNames:
    - dmtemplate
    singular: deploymentmanagertemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DeploymentManagerTemplate is the schema for a template that defines
          how to create a deployment manager.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          extensions:
            additionalProperties:
              type: string
            description: Extensions contains additional information that is associated
              to the template.
            type: object
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          nodeProfiles:
            description: NodeProfiles is a collection of named node profiles that
              will be used in the template.
            items:
              description: DeploymentManagerTemplateNodeProfile associates a name
                with a set of node settings.
              properties:
                extensions:
                  additionalProperties:
                    type: string
                  description: Extensions contains additional information associated
                    with the profile that can't be expressed in the other fields.
                  type: object
                name:
                  description: Name is the name of the profile.
                  type: string
              required:
              - name
              type: object
            minItems: 1
            type: array
          nodeSets:
            description: NodeSets is a collection of named sets of nodes that will
              be used in the template.
            items:
              description: DeploymentManagerTemplateNodeSet associates a name with
                the configuration of a set of nodes. For example, it is common to
                have a set of control plane nodes and a set of worker nodes where
                all the control plane nodes share the same hardware settings, but
                the worker nodes have different settings.
              properties:
                extensions:
                  additionalProperties:
                    type: string
                  description: Extensions contains additional information associated
                    with the node set that can't be expressed in the other fields.
                  type: object
                name:
                  description: Name is the name of the node set.
                  type: string
                profile:
                  description: Profile is the name of the profile that defines the
                    settings that will be used by nodes in this set.
                  type: string
              required:
              - name
              - profile
              type: object
            minItems: 1
            type: array
        type: object
    served: true
    storage: true
    subresources:
      status: {}
