---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.13.0
  name: clustertemplates.oran.openshift.io
spec:
  group: oran.openshift.io
  names:
    kind: ClusterTemplate
    listKind: ClusterTemplateList
    plural: clustertemplates
    singular: clustertemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterTemplate is the Schema for the clustertemplates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterTemplateSpec defines the desired state of ClusterTemplate
            properties:
              inputDataSchema:
                description: InputDataSchema encapsulates all the schemas required
                  for ClusterTemplate.
                properties:
                  clusterInstanceSchema:
                    description: ClusterInstanceSchema defines the parameters required
                      for provisioning. The parameter definitions should follow the
                      OpenAPI V3 schema and explicitly define required fields.
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                required:
                - clusterInstanceSchema
                type: object
              templates:
                description: Templates defines the references to the templates required
                  for ClusterTemplate.
                properties:
                  clusterInstanceDefaults:
                    description: ClusterInstanceDefaults defines a reference to a
                      configmap with default values for ClusterInstance
                    type: string
                required:
                - clusterInstanceDefaults
                type: object
            required:
            - inputDataSchema
            - templates
            type: object
          status:
            description: ClusterTemplateStatus defines the observed state of ClusterTemplate
            properties:
              clusterTemplateValidation:
                description: Tells if the schema provided in spec.inputDataSchema
                  is a valid JSON.
                properties:
                  clusterTemplateError:
                    description: Holds the error in case the ClusterTemplate is invalid.
                    type: string
                  clusterTemplateIsValid:
                    description: Says of the ClusterTemplate is valid or not.
                    type: boolean
                required:
                - clusterTemplateIsValid
                type: object
            required:
            - clusterTemplateValidation
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
